# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 14:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Browse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 21, 14, 56, 10, 698534, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expired',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 21, 14, 56, 10, 699939, tzinfo=utc)),
        ),
    ]
