# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 12:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Browse', '0008_auto_20170925_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expired',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 25, 12, 41, 49, 855328, tzinfo=utc)),
        ),
    ]
