# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 17:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Browse', '0009_auto_20170925_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expired',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 25, 17, 9, 34, 85028, tzinfo=utc)),
        ),
    ]
