# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 11:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Browse', '0010_auto_20170925_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bought',
            old_name='sell_price',
            new_name='cur_highest_bid',
        ),
        migrations.AddField(
            model_name='bought',
            name='buy_now_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bought',
            name='created_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='bought',
            name='expiration',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='bought',
            name='item_logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='bought',
            name='min_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='expired',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 27, 11, 38, 0, 366411, tzinfo=utc)),
        ),
    ]
