# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='user_credits',
            field=models.IntegerField(default=1000, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='user_dob',
            field=models.DateField(null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='register',
            name='user_email',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='user_mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='user_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='user_password',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
