# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20170826_1837'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
    ]
