# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0003_delete_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_dob', models.DateField(null=True, verbose_name='date of birth')),
                ('user_credits', models.IntegerField(default=1000, null=True)),
            ],
        ),
    ]
